import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUiProvider } from "./Components/NextUiProvider";
import UserContextProvider from "./Providers/UserContextProvider";
import Applayout from "./Components/Applayout.tsx";
import clsx from "clsx";
import { SuperTokensProvider } from "./Providers/SuperTokensProvider";
import SessionAuthProvider from "./Providers/SessionAuthProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SuperTokensProvider>
        <body
          className={clsx(
            inter.className,
            "h-screen overflow-hidden text-[#27313b]"
          )}
        >
          <SessionAuthProvider>{children}</SessionAuthProvider>
        </body>
      </SuperTokensProvider>
    </html>
  );
}
